# Generated by Django 2.0.2 on 2018-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nerong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerong_id', models.IntegerField(default=0)),
                ('nerong_title', models.CharField(max_length=200)),
                ('nerong_text', models.CharField(max_length=600)),
            ],
        ),
    ]
